### ISSUE TITLE
Homebridge Plugin?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Apollon77/ioBroker.siegenia#6]
I was wondering whether you have ever considered porting this to Homebridge? I've recently bought HS Window and I would love this being integrated to Homekit through Homebridge. I even considered using iOBroker, iOBroker.siegenia and then Homebridge IOBroker to get access but it would be probably much easier with native support.

**Comment by Apollon77** [comment]
Time wise (in general and also because of the fact that I do not have that much expereince in developing for homebridge) I did not considered this ... you're welcome to use the stuff from here and build a homebridge module out of it :-)

**Comment by PrzemyslawKlys** [comment]
Hello @Apollon77 - thank you for your help - I was able to figure out your code and create Homebridge plugin based on on it:
https://github.com/EvotecIT/homebridge-siegenia which now allows me to use it in Apple HomeKit! 

Thank you again, really appreciate quick feedback on the issue:
- https://github.com/Apollon77/ioBroker.siegenia/issues/239

I didn't get a response from Siegenia, but with ioBroker logs I was able to figure out what's getting sent and was is received. While I don't know typescript, or have knowledge on inner workings of homebridge with your help, with your JS code and GitHub Copilot I was able to force it to mostly write it for me :-)
